
exports.seed = function (knex, Promise) {
    // Deletes ALL existing entries
    return knex('products')
        .then(() => {
            // Inserts seed entries
            return knex('products').insert([
                {
                    categoryId: 1,
                    unitId: 1,
                    typeCargoId: 2,
                    name: 'lót Pu 08',
                    description: 'Lót Pu-08 được sản xuất dựa trên nhựa alkyd cao cấp, giúp lót bám tốt trên mọi chất liệu đồng thời che phủ khuyết tật của bề mặt, giúp bề mặt phẳng hơn tạo điều kiện cho lớp sơn phủ mặt bám chắc trên bề mặt vật liệu',
                    imageUrl: '',
                    isPublic: true,
                    purchasePrice: 35000,
                    salePrice: 53000,
                    minQuantity: 320,
                    isAvaiable: true,
                },
                {
                    categoryId: 1,
                    unitId: 1,
                    typeCargoId: 1,
                    name: 'N Butyl acetate',
                    description: 'n-Butyl acetate là hợp chất hữu cơ có công thức phân tử C6H12O2, dạng lỏng, không màu, có mùi dầu chuối, dễ cháy, tan được trong hầu hết các dung môi hữu cơ  như alcohol, glycol, ester, ketone, và tan ít trong nước',
                    imageUrl: '',
                    isPublic: false,
                    purchasePrice: 20500,
                    salePrice: 25000,
                    minQuantity: 4000,
                    isAvaiable: true,
                },
                {
                    categoryId: 1,
                    unitId: 1,
                    typeCargoId: 2,
                    name: 'lót Pu 02',
                    description: 'Lót Pu-02 được sản xuất dựa trên nhựa alkyd cao cấp, giúp lót bám tốt trên mọi chất liệu đồng thời che phủ khuyết tật của bề mặt, giúp bề mặt phẳng hơn tạo điều kiện cho lớp sơn phủ mặt bám chắc trên bề mặt vật liệu',
                    imageUrl: '',
                    isPublic: true,
                    purchasePrice: 38000,
                    salePrice: 65000,
                    minQuantity: 320,
                    isAvaiable: true,
                },
                {
                    categoryId: 1,
                    unitId: 1,
                    typeCargoId: 1,
                    name: 'Butyl A+',
                    description: 'Butyl A+ là hợp chất hữu cơ có công thức phân tử C6H12O2, dạng lỏng, không màu, có mùi dầu chuối, dễ cháy, tan được trong hầu hết các dung môi hữu cơ  như alcohol, glycol, ester, ketone, và tan ít trong nước',
                    imageUrl: '',
                    isPublic: true,
                    purchasePrice: 18000,
                    salePrice: 20000,
                    minQuantity: 4000,
                    isAvaiable: true,
                },
                {
                    categoryId: 1,
                    unitId: 1,
                    typeCargoId: 1,
                    name: 'Xăng thơm',
                    description: 'Xăng thơm là hợp chất hữu cơ có công thức phân tử C6H12O2, dạng lỏng, không màu, có mùi dầu chuối, dễ cháy, tan được trong hầu hết các dung môi hữu cơ  như alcohol, glycol, ester, ketone, và tan ít trong nước',
                    imageUrl: '',
                    isPublic: true,
                    purchasePrice: 17500,
                    salePrice: 19000,
                    minQuantity: 4000,
                    isAvaiable: true,
                },
                {
                    categoryId: 1,
                    unitId: 1,
                    typeCargoId: 2,
                    name: 'lót NC - 05',
                    description: 'Lót NC- 05 được sản xuất dựa trên nhựa alkyd cao cấp, giúp lót bám tốt trên mọi chất liệu đồng thời che phủ khuyết tật của bề mặt, giúp bề mặt phẳng hơn tạo điều kiện cho lớp sơn phủ mặt bám chắc trên bề mặt vật liệu',
                    imageUrl: '',
                    isPublic: true,
                    purchasePrice: 27000,
                    salePrice: 43000,
                    minQuantity: 320,
                    isAvaiable: true,
                },
                {
                    categoryId: 1,
                    unitId: 1,
                    typeCargoId: 2,
                    name: 'Lót NC - 02',
                    description: 'Lót NC- 02 được sản xuất dựa trên nhựa alkyd cao cấp, giúp lót bám tốt trên mọi chất liệu đồng thời che phủ khuyết tật của bề mặt, giúp bề mặt phẳng hơn tạo điều kiện cho lớp sơn phủ mặt bám chắc trên bề mặt vật liệu',
                    imageUrl: '',
                    isPublic: true,
                    purchasePrice: 30000,
                    salePrice: 48000,
                    minQuantity: 4000,
                    isAvaiable: true,
                },
                {
                    categoryId: 1,
                    unitId: 1,
                    typeCargoId: 2,
                    name: 'Lót công nghiệp',
                    description: 'Lót công nghiệp được sản xuất dựa trên nhựa alkyd cao cấp, giúp lót bám tốt trên mọi chất liệu đồng thời che phủ khuyết tật của bề mặt, giúp bề mặt phẳng hơn tạo điều kiện cho lớp sơn phủ mặt bám chắc trên bề mặt vật liệu',
                    imageUrl: '',
                    isPublic: true,
                    purchasePrice: 32000,
                    salePrice: 60000,
                    minQuantity: 4000,
                    isAvaiable: true,
                },
                {
                    categoryId: 1,
                    unitId: 1,
                    typeCargoId: 2,
                    name: 'lót Nâu - 01',
                    description: 'lót Nâu - 01 được sản xuất dựa trên nhựa alkyd cao cấp, giúp lót bám tốt trên mọi chất liệu đồng thời che phủ khuyết tật của bề mặt, giúp bề mặt phẳng hơn tạo điều kiện cho lớp sơn phủ mặt bám chắc trên bề mặt vật liệu',
                    imageUrl: '',
                    isPublic: true,
                    purchasePrice: 18000,
                    salePrice: 27000,
                    minQuantity: 320,
                    isAvaiable: true,
                },
                {
                    categoryId: 1,
                    unitId: 1,
                    typeCargoId: 2,
                    name: 'lót vàng - 01',
                    description: 'Lót vàng - 01 được sản xuất dựa trên nhựa alkyd cao cấp, giúp lót bám tốt trên mọi chất liệu đồng thời che phủ khuyết tật của bề mặt, giúp bề mặt phẳng hơn tạo điều kiện cho lớp sơn phủ mặt bám chắc trên bề mặt vật liệu',
                    imageUrl: '',
                    isPublic: true,
                    purchasePrice: 18000,
                    salePrice: 27000,
                    minQuantity: 4000,
                    isAvaiable: true,
                },
                {
                    categoryId: 1,
                    unitId: 1,
                    typeCargoId: 2,
                    name: 'Mờ 02 - 30%',
                    description: 'Mờ 02 - 30% được sản xuất dựa trên nhựa alkyd cao cấp. Đươc sử dụng làm sơn phủ lên gỗ, đồ mỹ nghệ mây tre đan với độ bóng 70% làm sản phẩm trở nên sang trọng tuyệt hảo',
                    imageUrl: '',
                    isPublic: true,
                    purchasePrice: 42000,
                    salePrice: 72000,
                    minQuantity: 320,
                    isAvaiable: true,
                },
                {
                    categoryId: 1,
                    unitId: 1,
                    typeCargoId: 2,
                    name: 'Mờ 02 - 50%',
                    description: 'Mờ 02- 50% được sản xuất dựa trên nhựa alkyd cao cấp. Đươc sử dụng làm sơn phủ lên gỗ, đồ mỹ nghệ mây tre đan với độ bóng 50% làm sản phẩm trở nên sang trọng tuyệt hảo',
                    imageUrl: '',
                    isPublic: true,
                    purchasePrice: 42000,
                    salePrice: 72000,
                    minQuantity: 4000,
                    isAvaiable: true,
                },
                {
                    categoryId: 1,
                    unitId: 1,
                    typeCargoId: 2,
                    name: 'Mờ 02 -75',
                    description: 'Mờ 02 - 75% được sản xuất dựa trên nhựa alkyd cao cấp. Đươc sử dụng làm sơn phủ lên gỗ, đồ mỹ nghệ mây tre đan với độ mờ 75% làm sản phẩm trở nên sang trọng tuyệt hảo',
                    imageUrl: '',
                    isPublic: true,
                    purchasePrice: 42000,
                    salePrice: 72000,
                    minQuantity: 320,
                    isAvaiable: true,
                },
                {
                    categoryId: 1,
                    unitId: 1,
                    typeCargoId: 2,
                    name: 'Mờ 02 - 100%',
                    description: 'Mờ 02- 50% được sản xuất dựa trên nhựa alkyd cao cấp. Đươc sử dụng làm sơn phủ lên gỗ, đồ mỹ nghệ mây tre đan với độ mờ 100% làm sản phẩm trở nên sang trọng tuyệt hảo',
                    imageUrl: '',
                    isPublic: true,
                    purchasePrice: 42000,
                    salePrice: 72000,
                    minQuantity: 4000,
                    isAvaiable: true,
                },
                {
                    categoryId: 1,
                    unitId: 1,
                    typeCargoId: 2,
                    name: 'Mờ 01 - 30%',
                    description: 'Mờ 01 - 30% được sản xuất dựa trên nhựa alkyd cao cấp. Đươc sử dụng làm sơn phủ lên gỗ, đồ mỹ nghệ mây tre đan với độ bóng 70% làm sản phẩm trở nên sang trọng tuyệt hảo',
                    imageUrl: '',
                    isPublic: true,
                    purchasePrice: 42000,
                    salePrice: 80000,
                    minQuantity: 320,
                    isAvaiable: true,
                },
                {
                    categoryId: 1,
                    unitId: 1,
                    typeCargoId: 2,
                    name: 'Mờ 01 - 50%',
                    description: 'Mờ 01- 50% được sản xuất dựa trên nhựa alkyd cao cấp. Đươc sử dụng làm sơn phủ lên gỗ, đồ mỹ nghệ mây tre đan với độ bóng 50% làm sản phẩm trở nên sang trọng tuyệt hảo',
                    imageUrl: '',
                    isPublic: true,
                    purchasePrice: 42000,
                    salePrice: 80000,
                    minQuantity: 4000,
                    isAvaiable: true,
                },
                {
                    categoryId: 1,
                    unitId: 1,
                    typeCargoId: 2,
                    name: 'Mờ 01 -75',
                    description: 'Mờ 01 - 75% được sản xuất dựa trên nhựa alkyd cao cấp. Đươc sử dụng làm sơn phủ lên gỗ, đồ mỹ nghệ mây tre đan với độ mờ 75% làm sản phẩm trở nên sang trọng tuyệt hảo',
                    imageUrl: '',
                    isPublic: true,
                    purchasePrice: 42000,
                    salePrice: 80000,
                    minQuantity: 320,
                    isAvaiable: true,
                },
                {
                    categoryId: 1,
                    unitId: 1,
                    typeCargoId: 2,
                    name: 'Mờ 01 - 100%',
                    description: 'Mờ 01- 50% được sản xuất dựa trên nhựa alkyd cao cấp. Đươc sử dụng làm sơn phủ lên gỗ, đồ mỹ nghệ mây tre đan với độ mờ 100% làm sản phẩm trở nên sang trọng tuyệt hảo',
                    imageUrl: '',
                    isPublic: true,
                    purchasePrice: 42000,
                    salePrice: 80000,
                    minQuantity: 4000,
                    isAvaiable: true,
                },
                {
                    categoryId: 1,
                    unitId: 1,
                    typeCargoId: 2,
                    name: 'Bóng TS',
                    description: 'Bóng TS được sản xuất dựa trên nhựa alkyd cao cấp. Đươc sử dụng làm sơn phủ lên gỗ, đồ mỹ nghệ mây tre đan với độ mờ 75% làm sản phẩm trở nên sang trọng tuyệt hảo',
                    imageUrl: '',
                    isPublic: true,
                    purchasePrice: 35000,
                    salePrice: 50000,
                    minQuantity: 320,
                    isAvaiable: true,
                },
                {
                    categoryId: 1,
                    unitId: 1,
                    typeCargoId: 2,
                    name: 'Bóng TC',
                    description: 'Bóng TC được sản xuất dựa trên nhựa alkyd cao cấp. Đươc sử dụng làm sơn phủ lên gỗ, đồ mỹ nghệ mây tre đan với độ mờ 100% làm sản phẩm trở nên sang trọng tuyệt hảo',
                    imageUrl: '',
                    isPublic: true,
                    purchasePrice: 35000,
                    salePrice: 65000,
                    minQuantity: 4000,
                    isAvaiable: true,
                },
                {
                    categoryId: 1,
                    unitId: 1,
                    typeCargoId: 2,
                    name: 'Bóng TE',
                    description: 'Bóng TE được sản xuất dựa trên nhựa alkyd cao cấp. Đươc sử dụng làm sơn phủ lên gỗ, đồ mỹ nghệ mây tre đan với độ mờ 100% làm sản phẩm trở nên sang trọng tuyệt hảo',
                    imageUrl: '',
                    isPublic: true,
                    purchasePrice: 38000,
                    salePrice: 70000,
                    minQuantity: 4000,
                    isAvaiable: true,
                },
                {
                    categoryId: 1,
                    unitId: 1,
                    typeCargoId: 2,
                    name: 'Bóng EX',
                    description: 'Bóng EX được sản xuất dựa trên nhựa alkyd cao cấp. Đươc sử dụng làm sơn phủ lên gỗ, đồ mỹ nghệ mây tre đan với độ mờ 100% làm sản phẩm trở nên sang trọng tuyệt hảo',
                    imageUrl: '',
                    isPublic: true,
                    purchasePrice: 45000,
                    salePrice: 85000,
                    minQuantity: 4000,
                    isAvaiable: true,
                },
                {
                    categoryId: 1,
                    unitId: 1,
                    typeCargoId: 2,
                    name: 'Cứng 404',
                    description: 'Cứng 404 được sản xuất dựa trên nhựa HDMI cao cấp. Đươc sử dụng làm thành phần đóng rắn cho sơn lót, sơn phủ',
                    imageUrl: '',
                    isPublic: true,
                    purchasePrice: 49000,
                    salePrice: 72000,
                    minQuantity: 4000,
                    isAvaiable: true,
                },
                {
                    categoryId: 1,
                    unitId: 1,
                    typeCargoId: 2,
                    name: 'Cứng 65%',
                    description: 'Cứng 65% được sản xuất dựa trên nhựa HDMI cao cấp. Đươc sử dụng làm thành phần đóng rắn cho sơn lót, sơn phủ',
                    imageUrl: '',
                    isPublic: true,
                    purchasePrice: 49000,
                    salePrice: 72000,
                    minQuantity: 4000,
                    isAvaiable: true,
                },
                {
                    categoryId: 1,
                    unitId: 1,
                    typeCargoId: 2,
                    name: 'Cứng 75%',
                    description: 'Cứng 75% được sản xuất dựa trên nhựa HDMI cao cấp với hàm lượng rắn 75%. Đươc sử dụng làm thành phần đóng rắn cho sơn lót, sơn phủ',
                    imageUrl: '',
                    isPublic: true,
                    purchasePrice: 59000,
                    salePrice: 80000,
                    minQuantity: 4000,
                    isAvaiable: true,
                },
            ]);
        });
};
