
exports.seed = function (knex, Promise) {
    // Deletes ALL existing entries
    return knex('customers')
        .then(() => {
            // Inserts seed entries
            return knex('customers').insert([
                {
                    customerGroupId: 6,                    
                    name: 'Tư Sim',
                    address: 'Giải phóng - Nam Định',
                    imageUrl: '',
                    phone: '0916678845',
                    email: 'thanhtung776@gmail.com',
                    CurentDebt: 0,
                    overdue: 10,
                    excessDebt: 10000000,
                    directorName: null,
                    bankNumber: null,
                    bankName: null,
                    companyName: null,
                    companyAdress: null,
                    taxCode: null,
                    fax: ''
                },
                {
                    customerGroupId: 5,                    
                    name: 'Mỹ Nghệ Nam Hà',
                    address: 'Giải phóng - Nam Định',
                    imageUrl: '',
                    phone: '0916545545',
                    email: 'mynghenamha@gmail.com',
                    CurentDebt: 0,
                    overdue: 10,
                    excessDebt: 10000000,
                    directorName: 'Nguyen Van Hien',
                    bankNumber: 320320100556,
                    bankName: 'Ngân hàng nông nghiệp Nam Định',
                    companyName: 'Công ty cổ phần Mỹ Nghệ Nam Hà',
                    companyAdress: 'Cầu Đá Nam Định',
                    taxCode: 354656458,
                    fax: ''
                },
                {
                    customerGroupId: 1,                    
                    name: 'Dũng Mai',
                    address: 'Giải phóng - Nam Định',
                    imageUrl: '',
                    phone: '0916678845',
                    email: 'thanhtung776@gmail.com',
                    CurentDebt: 0,
                    overdue: 10,
                    excessDebt: 10000000,
                    directorName: null,
                    bankNumber: null,
                    bankName: null,
                    companyName: null,
                    companyAdress: null,
                    taxCode: null,
                    fax: ''
                },
                {
                    customerGroupId: 1,                    
                    name: 'Dũng Tuyết',
                    address: 'Giải phóng - Nam Định',
                    imageUrl: '',
                    phone: '0916545545',
                    email: 'mynghenamha@gmail.com',
                    CurentDebt: 0,
                    overdue: 10,
                    excessDebt: 10000000,
                    directorName: 'Nguyen Van Hien',
                    bankNumber: 320320100556,
                    bankName: 'Ngân hàng nông nghiệp Nam Định',
                    companyName: 'Công ty cổ phần Mỹ Nghệ Nam Hà',
                    companyAdress: 'Cầu Đá Nam Định',
                    taxCode: 354656458,
                    fax: ''
                },
                {
                    customerGroupId: 1,                    
                    name: 'Hưng Thái Bình',
                    address: 'Giải phóng - Nam Định',
                    imageUrl: '',
                    phone: '0916678845',
                    email: 'thanhtung776@gmail.com',
                    CurentDebt: 0,
                    overdue: 10,
                    excessDebt: 10000000,
                    directorName: null,
                    bankNumber: null,
                    bankName: null,
                    companyName: null,
                    companyAdress: null,
                    taxCode: null,
                    fax: ''
                },
                {
                    customerGroupId: 1,                    
                    name: 'A Lục - Ninh Bình',
                    address: 'Giải phóng - Nam Định',
                    imageUrl: '',
                    phone: '0916545545',
                    email: 'mynghenamha@gmail.com',
                    CurentDebt: 0,
                    overdue: 10,
                    excessDebt: 10000000,
                    directorName: 'Nguyen Van Hien',
                    bankNumber: 320320100556,
                    bankName: 'Ngân hàng nông nghiệp Nam Định',
                    companyName: 'Công ty cổ phần Mỹ Nghệ Nam Hà',
                    companyAdress: 'Cầu Đá Nam Định',
                    taxCode: 354656458,
                    fax: ''
                },
                {
                    customerGroupId: 2,                    
                    name: 'Na Hùng',
                    address: 'Giải phóng - Nam Định',
                    imageUrl: '',
                    phone: '0916678845',
                    email: 'thanhtung776@gmail.com',
                    CurentDebt: 0,
                    overdue: 10,
                    excessDebt: 10000000,
                    directorName: null,
                    bankNumber: null,
                    bankName: null,
                    companyName: null,
                    companyAdress: null,
                    taxCode: null,
                    fax: ''
                },
                {
                    customerGroupId: 3,                    
                    name: 'Hưng Ngặt Kéo',
                    address: 'Giải phóng - Nam Định',
                    imageUrl: '',
                    phone: '0916545545',
                    email: 'mynghenamha@gmail.com',
                    CurentDebt: 0,
                    overdue: 10,
                    excessDebt: 10000000,
                    directorName: 'Nguyen Van Hien',
                    bankNumber: 320320100556,
                    bankName: 'Ngân hàng nông nghiệp Nam Định',
                    companyName: 'Công ty cổ phần Mỹ Nghệ Nam Hà',
                    companyAdress: 'Cầu Đá Nam Định',
                    taxCode: 354656458,
                    fax: ''
                },
                {
                    customerGroupId: 3,                    
                    name: 'Yết',
                    address: 'Giải phóng - Nam Định',
                    imageUrl: '',
                    phone: '0916678845',
                    email: 'thanhtung776@gmail.com',
                    CurentDebt: 0,
                    overdue: 10,
                    excessDebt: 10000000,
                    directorName: null,
                    bankNumber: null,
                    bankName: null,
                    companyName: null,
                    companyAdress: null,
                    taxCode: null,
                    fax: ''
                },
                {
                    customerGroupId: 3,                    
                    name: 'Mẫn Gôi',
                    address: 'Giải phóng - Nam Định',
                    imageUrl: '',
                    phone: '0916545545',
                    email: 'mynghenamha@gmail.com',
                    CurentDebt: 0,
                    overdue: 10,
                    excessDebt: 10000000,
                    directorName: 'Nguyen Van Hien',
                    bankNumber: 320320100556,
                    bankName: 'Ngân hàng nông nghiệp Nam Định',
                    companyName: 'Công ty cổ phần Mỹ Nghệ Nam Hà',
                    companyAdress: 'Cầu Đá Nam Định',
                    taxCode: 354656458,
                    fax: ''
                },
            ]);
        });
};
