export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_FAIL = "LOGIN_USER_FAIL";
export const LOGIN_USER_PENDING = "LOGIN_USER_PENDING";
export const SIGNUPFORM_CHANGED = "SIGNUPFORM_CHANGED";
export const SIGNUP_USER_SUCCESS = "SIGNUP_USER_SUCCESS";
export const SIGNUP_USER_FAIL = "SIGNUP_USER_FAIL";
export const SIGNUP_USER_PENDING = "SIGNUP_USER_PENDING";

