export const PASSWORD_CHANGED = 'PASSWORD_CHANGED';
export const EMAIL_CHANGED = 'EMAIL_CHANGED';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
//===================== Login =================================================//
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAIL = 'LOGIN_USER_FAIL';
export const LOGIN_USER_PENDING = 'LOGIN_USER_PENDING';
export const LOGIN_FORM_CHANGED = 'LOGIN_FORM_CHANGED';
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
//===================== Signup =================================================//
export const SIGNUPFORM_CHANGED = 'SIGNUPFORM_CHANGED';
export const SIGNUP_USER_SUCCESS = 'SIGNUP_USER_SUCCESS';
export const SIGNUP_USER_FAIL = 'SIGNUP_USER_FAIL';
export const SIGNUP_USER_PENDING = 'SIGNUP_USER_PENDING';
//===================== FlashMessage =================================================//
export const ADD_FLASH_MESSAGE = 'ADD_FLASH_MESSAGE';
export const SUCCESS_MESSAGE = 'SUCCESS_MESSAGE';
export const ERROR_MESSAGE = 'ERROR_MESSAGE';
export const WARNING_MESSAGE = 'WARNINGS_MESSAGE';
//========================= CATEGORY ==================================================
export const ADD_CATEGORY = 'ADD_CATEGORY';
export const CATEGORY_PENDING = 'ADD_CATEGORY_PENDING';
export const CATEGORY_CHANGE_FAIL = 'CATEGORY_CHANGE_FAIL';
export const CATEGORY_CHANGE_SUCCESS = 'CATEGORY_CHANGE_SUCCESS';
export const CATEGORY_CHANGE = 'CATEGORY_CHANGE';
export const CATEGORY_LOADED_SQLITE = 'CATEGORY_LOADED_SQLITE';
export const CATEGORY_DELETE_SUCCESS = 'CATEGORY_DELETE_SUCCESS';
export const RESET_CATEGORY_FORM = 'RESET_CATEGORY_FORM';
//========================= PRODUCT ==================================================
export const ADD_PRODUCT = 'ADD_PRODUCT';
export const PRODUCT_PENDING = 'PRODUCT_PENDING';
export const PRODUCT_CHANGE_FAIL = 'PRODUCT_CHANGE_FAIL';
export const PRODUCT_CHANGE_SUCCESS = 'PRODUCT_CHANGE_SUCCESS';
export const PRODUCT_CHANGE = 'PRODUCT_CHANGE';
export const PRODUCT_DELETE_SUCCESS = 'PRODUCT_DELETE_SUCCESS';
export const RESET_PRODUCT_FORM = 'RESET_PRODUCT_FORM';
export const PRODUCT_LOADED_SQLITE = 'PRODUCT_LOADED_SQLITE';
export const PRODUCT_LIST_LOADED_SQLITE = 'PRODUCT_LIST_LOADED_SQLITE';
export const LOAD_TYPE_CARGO_SUCCESS = 'LOAD_TYPE_CARGO_SUCCESS';
export const LOAD_UNIT_SUCCESS = 'LOAD_UNIT_SUCCESS';
//========================= Customer Group ==================================================
export const ADD_CUSTOMER_GROUP = 'ADD_CUSTOMER_GROUP';
export const CUSTOMER_GROUP_PENDING = 'ADD_CUSTOMER_GROUP_PENDING';
export const CUSTOMER_GROUP_CHANGE_FAIL = 'CUSTOMER_GROUP_CHANGE_FAIL';
export const CUSTOMER_GROUP_CHANGE_SUCCESS = 'CUSTOMER_GROUP_CHANGE_SUCCESS';
export const CUSTOMER_GROUP_CHANGE = 'CUSTOMER_GROUP_CHANGE';
export const CUSTOMER_GROUP_LOADED_SQLITE = 'CUSTOMER_GROUP_LOADED_SQLITE';
export const CUSTOMER_GROUP_DELETE_SUCCESS = 'CUSTOMER_GROUP_DELETE_SUCCESS';
export const RESET_CUSTOMER_GROUP_FORM = 'RESET_CUSTOMER_GROUP_FORM';
export const CUSTOMER_GROUP_LIST_LOADED_SQLITE = 'CUSTOMER_GROUP_LIST_LOADED_SQLITE';
