export const PASSWORD_CHANGED = 'PASSWORD_CHANGED';
export const EMAIL_CHANGED = 'EMAIL_CHANGED';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
//===================== Login =================================================//
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAIL = 'LOGIN_USER_FAIL';
export const LOGIN_USER_PENDING = 'LOGIN_USER_PENDING';
export const LOGIN_FORM_CHANGED = 'LOGIN_FORM_CHANGED';
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
//===================== Signup =================================================//
export const SIGNUPFORM_CHANGED = 'SIGNUPFORM_CHANGED';
export const SIGNUP_USER_SUCCESS = 'SIGNUP_USER_SUCCESS';
export const SIGNUP_USER_FAIL = 'SIGNUP_USER_FAIL';
export const SIGNUP_USER_PENDING = 'SIGNUP_USER_PENDING';
//===================== FlashMessage =================================================//
export const ADD_FLASH_MESSAGE = 'ADD_FLASH_MESSAGE';
export const SUCCESS_MESSAGE = 'SUCCESS_MESSAGE';
export const ERROR_MESSAGE = 'ERROR_MESSAGE';
export const WARNING_MESSAGE = 'WARNINGS_MESSAGE';
//========================= CATEGORY ==================================================
export const ADD_CATEGORY = 'ADD_CATEGORY';
export const CATEGORY_PENDING = 'ADD_CATEGORY_PENDING';
export const CATEGORY_CHANGE_FAIL = 'CATEGORY_CHANGE_FAIL';
export const CATEGORY_CHANGE_SUCCESS = 'CATEGORY_CHANGE_SUCCESS';
export const CATEGORY_CHANGE = 'CATEGORY_CHANGE';
export const CATEGORY_LOADED_SQLITE = 'CATEGORY_LOADED_SQLITE';
export const CATEGORY_DELETE_SUCCESS = 'CATEGORY_DELETE_SUCCESS';
export const RESET_CATEGORY_FORM = 'RESET_CATEGORY_FORM';
//========================= PRODUCT ==================================================
export const ADD_PRODUCT = 'ADD_PRODUCT';
export const PRODUCT_PENDING = 'PRODUCT_PENDING';
export const PRODUCT_CHANGE_FAIL = 'PRODUCT_CHANGE_FAIL';
export const PRODUCT_CHANGE_SUCCESS = 'PRODUCT_CHANGE_SUCCESS';
export const PRODUCT_CHANGE = 'PRODUCT_CHANGE';
export const PRODUCT_DELETE_SUCCESS = 'PRODUCT_DELETE_SUCCESS';
export const RESET_PRODUCT_FORM = 'RESET_PRODUCT_FORM';
export const PRODUCT_LOADED_SQLITE = 'PRODUCT_LOADED_SQLITE';
export const PRODUCT_LIST_LOADED_SQLITE = 'PRODUCT_LIST_LOADED_SQLITE';
export const LOAD_TYPE_CARGO_SUCCESS = 'LOAD_TYPE_CARGO_SUCCESS';
export const LOAD_UNIT_SUCCESS = 'LOAD_UNIT_SUCCESS';
export const TOGGLE_PRODUCT_TO_SELECT_LIST = 'TOGGLE_PRODUCT_TO_SELECT_LIST';
export const RESET_SELECTED_PRODUCT = 'RESET_SELECTED_PRODUCT';
//========================= Customer Group ==================================================
export const ADD_CUSTOMER_GROUP = 'ADD_CUSTOMER_GROUP';
export const CUSTOMER_GROUP_PENDING = 'ADD_CUSTOMER_GROUP_PENDING';
export const CUSTOMER_GROUP_CHANGE_FAIL = 'CUSTOMER_GROUP_CHANGE_FAIL';
export const CUSTOMER_GROUP_CHANGE_SUCCESS = 'CUSTOMER_GROUP_CHANGE_SUCCESS';
export const CUSTOMER_GROUP_CHANGE = 'CUSTOMER_GROUP_CHANGE';
export const CUSTOMER_GROUP_LOADED_SQLITE = 'CUSTOMER_GROUP_LOADED_SQLITE';
export const CUSTOMER_GROUP_DELETE_SUCCESS = 'CUSTOMER_GROUP_DELETE_SUCCESS';
export const RESET_CUSTOMER_GROUP_FORM = 'RESET_CUSTOMER_GROUP_FORM';
export const CUSTOMER_GROUP_LIST_LOADED_SQLITE = 'CUSTOMER_GROUP_LIST_LOADED_SQLITE';
//========================= Customers ==================================================
export const ADD_CUSTOMER = 'ADD_CUSTOMER';
export const CUSTOMER_PENDING = 'ADD_CUSTOMER_PENDING';
export const CUSTOMER_CHANGE_FAIL = 'CUSTOMER_CHANGE_FAIL';
export const CUSTOMER_CHANGE_SUCCESS = 'CUSTOMER_CHANGE_SUCCESS';
export const CUSTOMER_CHANGE = 'CUSTOMER_CHANGE';
export const CUSTOMER_LOADED_SQLITE = 'CUSTOMER_LOADED_SQLITE';
export const CUSTOMER_DELETE_SUCCESS = 'CUSTOMER_DELETE_SUCCESS';
export const RESET_CUSTOMER_FORM = 'RESET_CUSTOMER_FORM';
export const CUSTOMER_LIST_LOADED_SQLITE = 'CUSTOMER_LIST_LOADED_SQLITE';
export const CUSTOMER_DEBT_LOADED_SQLITE = 'CUSTOMER_DEBT_LOADED_SQLITE';
//========================= Customers ==================================================
export const ADD_QUOCTE = 'ADD_QUOCTE';
export const QUOCTE_PENDING = 'ADD_QUOCTE_PENDING';
export const QUOCTE_CHANGE_FAIL = 'QUOCTE_CHANGE_FAIL';
export const QUOCTE_CHANGE_SUCCESS = 'QUOCTE_CHANGE_SUCCESS';
export const QUOCTE_CHANGE = 'QUOCTE_CHANGE';
export const QUOCTE_LOADED_SQLITE = 'QUOCTE_LOADED_SQLITE';
export const QUOCTE_DELETE_SUCCESS = 'QUOCTE_DELETE_SUCCESS';
export const RESET_QUOCTE_FORM = 'RESET_QUOCTE_FORM';
export const QUOCTE_LIST_LOADED_SQLITE = 'QUOCTE_LIST_LOADED_SQLITE';
export const QUOCTE_DETAIL_CHANGE = 'QUOCTE_DETAIL_CHANGE';
export const SELECTED_PRODUCT_TO_QUOCTE_DETAIL = 'SELECTED_PRODUCT_TO_QUOCTE_DETAIL';
//========================= Sale Ỏder ==================================================
export const ADD_SALE_ORDER = 'ADD_SALE_ORDER';
export const SALE_ORDER_PENDING = 'ADD_SALE_ORDER_PENDING';
export const SALE_ORDER_CHANGE_FAIL = 'SALE_ORDER_CHANGE_FAIL';
export const SALE_ORDER_CHANGE_SUCCESS = 'SALE_ORDER_CHANGE_SUCCESS';
export const SALE_ORDER_CHANGE = 'SALE_ORDER_CHANGE';
export const SALE_ORDER_LOADED_SQLITE = 'SALE_ORDER_LOADED_SQLITE';
export const SALE_ORDER_DELETE_SUCCESS = 'SALE_ORDER_DELETE_SUCCESS';
export const RESET_SALE_ORDER_FORM = 'RESET_SALE_ORDER_FORM';
export const SALE_ORDER_LIST_LOADED_SQLITE = 'SALE_ORDER_LIST_LOADED_SQLITE';
export const SALE_ORDER_DETAIL_CHANGE = 'SALE_ORDER_DETAIL_CHANGE';
export const SELECTED_PRODUCT_TO_SALE_ORDER_DETAIL = 'SELECTED_PRODUCT_TO_SALE_ORDER_DETAIL';
export const LOAD_TAX_SUCCESS = 'LOAD_TAX_SUCCESS';